[package]
authors = ["Martin Heistermann <git@mheistermann.de>"]
name = "lightfield_playground"
version = "0.1.0"

[dependencies]
cgmath = "0.9.1"
env_logger = "0.3.3"
image = "0.10.0"
lightfield_loader = ">=0.3.0"
log = "0.3.6"
